trigger:
  branches:
    include:
      - master

jobs:
- job: BuildAndRunDocker
  displayName: 'Build and Run Docker Image'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      # Build Docker image
      docker build -t my-php-app:latest .
    displayName: 'Build Docker Image'

  - script: |
      # Run the Docker container locally
      docker run -dp 8000:50 --name php-container --rm my-php-app:latest
    displayName: 'Run Docker Container'

